<div class="fitur-users">
    <div class="search-date">
        <input type="date">
    </div>
    <div class="fitur-search">
        <input type="text">
        <button type="button"> Search</button>
    </div>
</div>

<div class="transaction-users" style="overflow-x: auto;">
    <table class="transaction-users-detail">
        <thead>
            <tr>
                <th>No</th>
                <th>Id</th>
                <th>Tanggal</th>
                <th>Nama Pelanggan</th>
                <th>Nama Admin</th>
                <th>Alamat</th>
                <th>Nomor HP</th>
                <th>Jenis Pelayanan</th>
                <th>Harga</th>
                <th>Quantity</th>
                <th>Total</th>
                <th>Jenis Pembayaran</th>
                <th>Status</th>
                <th>Edit</th>
                <th>Hapus</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>001</td>
                <td>12 September 2024</td>
                <td>Sumiati</td>
                <td>Karin</td>
                <td>Cibendo</td>
                <td>085777915465</td>
                <td>Express</td>
                <td>5000</td>
                <td>5Kg</td>
                <td>25000</td>
                <td>Lunas</td>
                <td>Selesai</td>
                <td>Edit</td>
                <td>Hapus</td>
            </tr>
            <tr>
                <td>1</td>
                <td>001</td>
                <td>12 September 2024</td>
                <td>Sumiati</td>
                <td>Karin</td>
                <td>Cibendo</td>
                <td>085777915465</td>
                <td>Express</td>
                <td>5000</td>
                <td>5Kg</td>
                <td>25000</td>
                <td>Lunas</td>
                <td>Selesai</td>
                <td>Edit</td>
                <td>Hapus</td>
            </tr>
            <tr>
                <td>1</td>
                <td>001</td>
                <td>12 September 2024</td>
                <td>Sumiati</td>
                <td>Karin</td>
                <td>Cibendo</td>
                <td>085777915465</td>
                <td>Express</td>
                <td>5000</td>
                <td>5Kg</td>
                <td>25000</td>
                <td>Lunas</td>
                <td>Selesai</td>
                <td>Edit</td>
                <td>Hapus</td>
            </tr>
            <tr>
                <td>1</td>
                <td>001</td>
                <td>12 September 2024</td>
                <td>Sumiati</td>
                <td>Karin</td>
                <td>Cibendo</td>
                <td>085777915465</td>
                <td>Express</td>
                <td>5000</td>
                <td>5Kg</td>
                <td>25000</td>
                <td>Lunas</td>
                <td>Selesai</td>
                <td>Edit</td>
                <td>Hapus</td>
            </tr>
            <tr>
                <td>1</td>
                <td>001</td>
                <td>12 September 2024</td>
                <td>Sumiati</td>
                <td>Karin</td>
                <td>Cibendo</td>
                <td>085777915465</td>
                <td>Express</td>
                <td>5000</td>
                <td>5Kg</td>
                <td>25000</td>
                <td>Lunas</td>
                <td>Selesai</td>
                <td>Edit</td>
                <td>Hapus</td>
            </tr>
            <tr>
                <td>1</td>
                <td>001</td>
                <td>12 September 2024</td>
                <td>Sumiati</td>
                <td>Karin</td>
                <td>Cibendo</td>
                <td>085777915465</td>
                <td>Express</td>
                <td>5000</td>
                <td>5Kg</td>
                <td>25000</td>
                <td>Lunas</td>
                <td>Selesai</td>
                <td>Edit</td>
                <td>Hapus</td>
            </tr>
            <tr>
                <td>1</td>
                <td>001</td>
                <td>12 September 2024</td>
                <td>Sumiati</td>
                <td>Karin</td>
                <td>Cibendo</td>
                <td>085777915465</td>
                <td>Express</td>
                <td>5000</td>
                <td>5Kg</td>
                <td>25000</td>
                <td>Lunas</td>
                <td>Selesai</td>
                <td>Edit</td>
                <td>Hapus</td>
            </tr>
            <tr>
                <td>1</td>
                <td>001</td>
                <td>12 September 2024</td>
                <td>Sumiati</td>
                <td>Karin</td>
                <td>Cibendo</td>
                <td>085777915465</td>
                <td>Express</td>
                <td>5000</td>
                <td>5Kg</td>
                <td>25000</td>
                <td>Lunas</td>
                <td>Selesai</td>
                <td>Edit</td>
                <td>Hapus</td>
            </tr>
            <tr>
                <td>1</td>
                <td>001</td>
                <td>12 September 2024</td>
                <td>Sumiati</td>
                <td>Karin</td>
                <td>Cibendo</td>
                <td>085777915465</td>
                <td>Express</td>
                <td>5000</td>
                <td>5Kg</td>
                <td>25000</td>
                <td>Lunas</td>
                <td>Selesai</td>
                <td>Edit</td>
                <td>Hapus</td>
            </tr>
            <tr>
                <td>1</td>
                <td>001</td>
                <td>12 September 2024</td>
                <td>Sumiati</td>
                <td>Karin</td>
                <td>Cibendo</td>
                <td>085777915465</td>
                <td>Express</td>
                <td>5000</td>
                <td>5Kg</td>
                <td>25000</td>
                <td>Lunas</td>
                <td>Selesai</td>
                <td>Edit</td>
                <td>Hapus</td>
            </tr>
            <tr>
                <td>1</td>
                <td>001</td>
                <td>12 September 2024</td>
                <td>Sumiati</td>
                <td>Karin</td>
                <td>Cibendo</td>
                <td>085777915465</td>
                <td>Express</td>
                <td>5000</td>
                <td>5Kg</td>
                <td>25000</td>
                <td>Lunas</td>
                <td>Selesai</td>
                <td>Edit</td>
                <td>Hapus</td>
            </tr>
            <tr>
                <td>1</td>
                <td>001</td>
                <td>12 September 2024</td>
                <td>Sumiati</td>
                <td>Karin</td>
                <td>Cibendo</td>
                <td>085777915465</td>
                <td>Express</td>
                <td>5000</td>
                <td>5Kg</td>
                <td>25000</td>
                <td>Lunas</td>
                <td>Selesai</td>
                <td>Edit</td>
                <td>Hapus</td>
            </tr>
            <tr>
                <td>1</td>
                <td>001</td>
                <td>12 September 2024</td>
                <td>Sumiati</td>
                <td>Karin</td>
                <td>Cibendo</td>
                <td>085777915465</td>
                <td>Express</td>
                <td>5000</td>
                <td>5Kg</td>
                <td>25000</td>
                <td>Lunas</td>
                <td>Selesai</td>
                <td>Edit</td>
                <td>Hapus</td>
            </tr>
            <tr>
                <td>1</td>
                <td>001</td>
                <td>12 September 2024</td>
                <td>Sumiati</td>
                <td>Karin</td>
                <td>Cibendo</td>
                <td>085777915465</td>
                <td>Express</td>
                <td>5000</td>
                <td>5Kg</td>
                <td>25000</td>
                <td>Lunas</td>
                <td>Selesai</td>
                <td>Edit</td>
                <td>Hapus</td>
            </tr>
            <tr>
                <td>1</td>
                <td>001</td>
                <td>12 September 2024</td>
                <td>Sumiati</td>
                <td>Karin</td>
                <td>Cibendo</td>
                <td>085777915465</td>
                <td>Express</td>
                <td>5000</td>
                <td>5Kg</td>
                <td>25000</td>
                <td>Lunas</td>
                <td>Selesai</td>
                <td>Edit</td>
                <td>Hapus</td>
            </tr>
            <tr>
                <td>1</td>
                <td>001</td>
                <td>12 September 2024</td>
                <td>Sumiati</td>
                <td>Karin</td>
                <td>Cibendo</td>
                <td>085777915465</td>
                <td>Express</td>
                <td>5000</td>
                <td>5Kg</td>
                <td>25000</td>
                <td>Lunas</td>
                <td>Selesai</td>
                <td>Edit</td>
                <td>Hapus</td>
            </tr>
            <tr>
                <td>1</td>
                <td>001</td>
                <td>12 September 2024</td>
                <td>Sumiati</td>
                <td>Karin</td>
                <td>Cibendo</td>
                <td>085777915465</td>
                <td>Express</td>
                <td>5000</td>
                <td>5Kg</td>
                <td>25000</td>
                <td>Lunas</td>
                <td>Selesai</td>
                <td>Edit</td>
                <td>Hapus</td>
            </tr>
            <tr>
                <td>1</td>
                <td>001</td>
                <td>12 September 2024</td>
                <td>Sumiati</td>
                <td>Karin</td>
                <td>Cibendo</td>
                <td>085777915465</td>
                <td>Express</td>
                <td>5000</td>
                <td>5Kg</td>
                <td>25000</td>
                <td>Lunas</td>
                <td>Selesai</td>
                <td>Edit</td>
                <td>Hapus</td>
            </tr>
            <tr>
                <td>1</td>
                <td>001</td>
                <td>12 September 2024</td>
                <td>Sumiati</td>
                <td>Karin</td>
                <td>Cibendo</td>
                <td>085777915465</td>
                <td>Express</td>
                <td>5000</td>
                <td>5Kg</td>
                <td>25000</td>
                <td>Lunas</td>
                <td>Selesai</td>
                <td>Edit</td>
                <td>Hapus</td>
            </tr>
            <tr>
                <td>1</td>
                <td>001</td>
                <td>12 September 2024</td>
                <td>Sumiati</td>
                <td>Karin</td>
                <td>Cibendo</td>
                <td>085777915465</td>
                <td>Express</td>
                <td>5000</td>
                <td>5Kg</td>
                <td>25000</td>
                <td>Lunas</td>
                <td>Selesai</td>
                <td>Edit</td>
                <td>Hapus</td>
            </tr>
            <tr>
                <td>1</td>
                <td>001</td>
                <td>12 September 2024</td>
                <td>Sumiati</td>
                <td>Karin</td>
                <td>Cibendo</td>
                <td>085777915465</td>
                <td>Express</td>
                <td>5000</td>
                <td>5Kg</td>
                <td>25000</td>
                <td>Lunas</td>
                <td>Selesai</td>
                <td>Edit</td>
                <td>Hapus</td>
            </tr>
            <tr>
                <td>1</td>
                <td>001</td>
                <td>12 September 2024</td>
                <td>Sumiati</td>
                <td>Karin</td>
                <td>Cibendo</td>
                <td>085777915465</td>
                <td>Express</td>
                <td>5000</td>
                <td>5Kg</td>
                <td>25000</td>
                <td>Lunas</td>
                <td>Selesai</td>
                <td>Edit</td>
                <td>Hapus</td>
            </tr>
            <tr>
                <td>1</td>
                <td>001</td>
                <td>12 September 2024</td>
                <td>Sumiati</td>
                <td>Karin</td>
                <td>Cibendo</td>
                <td>085777915465</td>
                <td>Express</td>
                <td>5000</td>
                <td>5Kg</td>
                <td>25000</td>
                <td>Lunas</td>
                <td>Selesai</td>
                <td>Edit</td>
                <td>Hapus</td>
            </tr>
        </tbody>
    </table>
</div>